# Generated by Django 4.0.3 on 2023-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True, verbose_name='ツイートID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名前')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ユーザーID')),
                ('screen_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ユーザーネーム')),
                ('text', models.TextField(blank=True, null=True, verbose_name='ツイート文')),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('html', models.TextField(verbose_name='埋め込みコード')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '歌い手',
                'verbose_name_plural': '歌い手リスト',
            },
        ),
    ]
