# Generated by Django 4.0.3 on 2023-02-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tweet_id',
            field=models.CharField(max_length=100, verbose_name='ツイートID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ユーザーID'),
        ),
    ]
